Fixed Save to pdf and added new features
HoareLea/SAM_UI pull request #117
Opened 2023-09-22 14:12 UTC by MaciejDengusiak

### NOTE: Depends on

   
### Issues addressed by this PR

Fixes #

### Test files

### Additional comments

2023-09-25 10:04 UTC, ZiolkowskiJakub requested changes

2023-09-25 10:04 UTC, ZiolkowskiJakub commented on Mollier/SAM.Core.Mollier.UI/SAM.Core.Mollier.UI.csproj
> +    <Reference Include="Aspose.Imaging">
Do we need that?

2023-09-25 10:04 UTC, ZiolkowskiJakub commented on Mollier/SAM.Core.Mollier.UI/SAM.Core.Mollier.UI.csproj
> +      <HintPath>F:\EMFtoPDF\net5.0\Aspose.Imaging.dll</HintPath>
Do NOT use local absolute path in this case

2023-09-25 10:04 UTC, ZiolkowskiJakub commented on Mollier/SAM.Core.Mollier.UI/Temporary/ExportPDF.cs
> +using Aspose.Imaging;
Do we need that?

2023-09-25 10:09 UTC, MaciejDengusiak commented on Mollier/SAM.Core.Mollier.UI/Temporary/ExportPDF.cs
> +using Aspose.Imaging;
DONE

2023-09-26 07:12 UTC, ZiolkowskiJakub approved these changes

2023-09-26 07:12 UTC, merged